# Pivot tabulky

In [11]:
import pandas as pd

In [6]:
pd.options.display.float_format = '{:.2f}'.format
# pd.reset_option('display.float_format')

In [2]:
cholesterol = pd.read_csv("pivot_cholesterol.csv")
cholesterol.head()

    fdc_id  amount nutrient_name branded_food_category
0  1107295     0.0   Cholesterol                Chipsy
1  1107475    65.0   Cholesterol                  Sýry
2  1108349     0.0   Cholesterol              Cereálie
3  1109393   100.0   Cholesterol                  Sýry
4  1109400    36.0   Cholesterol               Sušenky

In [7]:
# 0-20 nizky
# 20-100 stredni
# vice nez 100 vysoky
# bins & labels - standardni oznaceni

bins = [0, 20, 100, float('inf')]
labels = ["nizky", "stredni", "vysoky"]

## funkce CUT
cholesterol["category"] = pd.cut(cholesterol["amount"], bins=bins, labels=labels)
cholesterol

       fdc_id  amount nutrient_name branded_food_category category
0     1107295    0.00   Cholesterol                Chipsy      NaN
1     1107475   65.00   Cholesterol                  Sýry  stredni
2     1108349    0.00   Cholesterol              Cereálie      NaN
3     1109393  100.00   Cholesterol                  Sýry  stredni
4     1109400   36.00   Cholesterol               Sušenky  stredni
...       ...     ...           ...                   ...      ...
2975  2659382   83.00   Cholesterol                  Sýry  stredni
2976  2660573   60.00   Cholesterol                  Sýry  stredni
2977  2660613    0.00   Cholesterol          Slané snacky      NaN
2978  2661380    0.00   Cholesterol                Chipsy      NaN
2979  2662107   42.00   Cholesterol                  Sýry  stredni

[2980 rows x 5 columns]

In [8]:
pd.crosstab(cholesterol["branded_food_category"], cholesterol["category"])

category               nizky  stredni  vysoky
branded_food_category
Cereálie                   3        0       0
Chipsy                     5        3       0
Cukrovinky                60       18       0
Další snacky               6       31      20
En. tyčinky               31       16       1
Nakl. zelenina            15       11       1
Pečivo                     8       23       0
Slané snacky              41        6       0
Sušenky                   36       75       3
Sýry                      27      259     101
Zmrzlina                  59      185       6
Čokoláda                  79       34       0

In [9]:
# funkce CROSSTAB

pd.crosstab(index=cholesterol["branded_food_category"], 
            columns=cholesterol["category"],
            margins=True,
            normalize="columns").style.format("{:.2%}")

In [13]:
cholesterol_fiber = pd.read_csv("pivot_cholesterol_fiber.csv")
cholesterol_fiber.head()

    fdc_id  amount nutrient_name branded_food_category
0  1107295    0.00   Cholesterol                Chipsy
1  1107475   65.00   Cholesterol                  Sýry
2  1108349    0.00   Cholesterol              Cereálie
3  1109393  100.00   Cholesterol                  Sýry
4  1109400   36.00   Cholesterol               Sušenky

In [14]:
pd.crosstab(index=cholesterol_fiber["branded_food_category"],
            columns=cholesterol_fiber["nutrient_name"])

nutrient_name          Cholesterol  Fiber, total dietary
branded_food_category
Cereálie                       170                   183
Chipsy                         214                   220
Cukrovinky                     295                   294
Další snacky                   137                   126
En. tyčinky                    180                   187
Nakl. zelenina                 127                   123
Pečivo                         236                   244
Slané snacky                   479                   498
Sušenky                        264                   266
Sýry                           400                   382
Zmrzlina                       296                   287
Čokoláda                       182                   186

In [15]:
pd.crosstab(index=cholesterol_fiber["branded_food_category"],
            columns=cholesterol_fiber["nutrient_name"],
            values=cholesterol_fiber["amount"],
            aggfunc="mean")

nutrient_name          Cholesterol  Fiber, total dietary
branded_food_category
Cereálie                      0.24                  7.54
Chipsy                        0.95                  5.42
Cukrovinky                    5.50                  1.38
Další snacky                 34.85                  3.28
En. tyčinky                   6.45                  8.78
Nakl. zelenina                6.71                  1.89
Pečivo                        5.31                  3.74
Slané snacky                  1.53                  7.23
Sušenky                      18.73                  2.28
Sýry                         76.84                  0.17
Zmrzlina                     49.16                  1.18
Čokoláda                     11.79                  4.79

## Cvičení

### Booking

In [71]:
hotel_bookings = pd.read_csv("hotel_bookings.csv")
hotel_bookings.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.00,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.00,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03

In [72]:
pd.crosstab(hotel_bookings["hotel"], hotel_bookings["is_canceled"], margins=True)

is_canceled       0      1     All
hotel
City Hotel    46228  33102   79330
Resort Hotel  28938  11122   40060
All           75166  44224  119390

In [73]:
city = hotel_bookings[hotel_bookings["hotel"] == "City Hotel"]

In [80]:
bins = [0, 7, 30, 180, float("inf")]
labels = ["Last minute", "Short-term", "Medium-term", "Long-term"]

city["Reservation_Category"] = pd.cut(city["lead_time"], bins=bins, labels=labels)

C:\Users\Aneta\AppData\Local\Temp\ipykernel_28028\25954367.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  city["Reservation_Category"] = pd.cut(city["lead_time"], bins=bins, labels=labels)

In [81]:
pd.crosstab(city["Reservation_Category"], city["is_canceled"], margins=True)

is_canceled               0      1    All
Reservation_Category
Last minute            6653   1046   7699
Short-term             8674   3880  12554
Medium-term           21974  17046  39020
Long-term              6091  10857  16948
All                   43392  32829  76221

### Titanic a další pivot tabulky (bonus)

In [82]:
titanic = pd.read_csv("titanic.csv")
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.00,1,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.00,1,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.00,0,0,STON/O2. 3101282,7.92,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.00,1,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.00,0,0,373450,8.05,NaN,S

In [83]:
pd.crosstab(titanic["Pclass"], titanic["Survived"], margins=True)

Survived    0    1  All
Pclass
1          80  136  216
2          97   87  184
3         372  119  491
All       549  342  891

# Datum a čas a metoda shift

In [28]:
signal_monitoring = pd.read_csv("signal_monitoring.csv")
signal_monitoring

         event_type      event_date_time
0       signal lost  2021-02-03 00:40:08
1   signal restored  2021-02-03 01:14:11
2       signal lost  2021-02-05 19:14:19
3   signal restored  2021-02-05 19:46:29
4       signal lost  2021-02-06 14:31:34
5   signal restored  2021-02-06 14:48:24
6       signal lost  2021-02-08 04:59:20
7   signal restored  2021-02-08 05:38:29
8       signal lost  2021-02-09 14:21:25
9   signal restored  2021-02-09 14:42:22
10      signal lost  2021-02-09 20:07:49
11  signal restored  2021-02-09 20:31:30
12      signal lost  2021-02-12 03:49:42
13  signal restored  2021-02-12 04:26:48
14      signal lost  2021-02-12 16:53:17
15  signal restored  2021-02-12 17:18:18
16      signal lost  2021-02-13 21:15:48
17  signal restored  2021-02-13 21:31:22
18      signal lost  2021-02-15 07:19:44
19  signal restored  2021-02-15 08:10:17
20      signal lost  2021-02-16 09:24:59
21  signal restored  2021-02-16 09:38:25
22      signal lost  2021-02-18 01:48:55
23  signal restored  2021-02-18 02:36:30
24      signal lost  2021-02-19 21:36:04
25  signal restored  2021-02-19 21:48:37
26      signal lost  2021-02-22 09:58:49
27  signal restored  2021-02-22 10:58:35

In [29]:
signal_monitoring["event_date_time"] = pd.to_datetime(signal_monitoring["event_date_time"])

In [30]:
signal_monitoring["event_date"] = signal_monitoring["event_date_time"].dt.date

In [31]:
signal_monitoring["event_date_time"].dt.daysinmonth

0     28
1     28
2     28
3     28
4     28
5     28
6     28
7     28
8     28
9     28
10    28
11    28
12    28
13    28
14    28
15    28
16    28
17    28
18    28
19    28
20    28
21    28
22    28
23    28
24    28
25    28
26    28
27    28
Name: event_date_time, dtype: int32

In [41]:
signal_monitoring["event_end_date_time"] = signal_monitoring["event_date_time"].shift(periods=-1)
signal_monitoring

,event_type,event_date_time,event_date,event_end_date_time,outage_length
0,signal lost,2021-02-03 00:40:08,2021-02-03,2021-02-05 19:14:19,0 days 00:34:03
1,signal lost,2021-02-05 19:14:19,2021-02-05,2021-02-06 14:31:34,0 days 00:32:10
2,signal lost,2021-02-06 14:31:34,2021-02-06,2021-02-08 04:59:20,0 days 00:16:50
3,signal lost,2021-02-08 04:59:20,2021-02-08,2021-02-09 14:21:25,0 days 00:39:09
4,signal lost,2021-02-09 14:21:25,2021-02-09,2021-02-09 20:07:49,0 days 00:20:57
5,signal lost,2021-02-09 20:07:49,2021-02-09,2021-02-12 03:49:42,0 days 00:23:41
6,signal lost,2021-02-12 03:49:42,2021-02-12,2021-02-12 16:53:17,0 days 00:37:06
7,signal lost,2021-02-12 16:53:17,2021-02-12,2021-02-13 21:15:48,0 days 00:25:01
8,signal lost,2021-02-13 21:15:48,2021-02-13,2021-02-15 07:19:44,0 days 00:15:34
9,signal lost,2021-02-15 07:19:44,2021-02-15,2021-02-16 09:24:59,0 days 00:50:33
10,signal lost,2021-02-16 09:24:59,2021-02-16,2021-02-18 01:48:55,0 days 00:13:26
11,signal lost,2021-02-18 01:48:55,2021-02-18,2021-02-19 21:36:04,0 days 00:47:35
12,signal lost,2021-02-19 21:36:04,2021-02-19,2021-02-22 09:58:49,0 days 00:12:33
13,signal lost,2021-02-22 09:58:49,2021-02-22,NaT,0 days 00:59:46

In [42]:
signal_monitoring = signal_monitoring[signal_monitoring["event_type"] == "signal lost"].reset_index(drop=True)
signal_monitoring

,event_type,event_date_time,event_date,event_end_date_time,outage_length
0,signal lost,2021-02-03 00:40:08,2021-02-03,2021-02-05 19:14:19,0 days 00:34:03
1,signal lost,2021-02-05 19:14:19,2021-02-05,2021-02-06 14:31:34,0 days 00:32:10
2,signal lost,2021-02-06 14:31:34,2021-02-06,2021-02-08 04:59:20,0 days 00:16:50
3,signal lost,2021-02-08 04:59:20,2021-02-08,2021-02-09 14:21:25,0 days 00:39:09
4,signal lost,2021-02-09 14:21:25,2021-02-09,2021-02-09 20:07:49,0 days 00:20:57
5,signal lost,2021-02-09 20:07:49,2021-02-09,2021-02-12 03:49:42,0 days 00:23:41
6,signal lost,2021-02-12 03:49:42,2021-02-12,2021-02-12 16:53:17,0 days 00:37:06
7,signal lost,2021-02-12 16:53:17,2021-02-12,2021-02-13 21:15:48,0 days 00:25:01
8,signal lost,2021-02-13 21:15:48,2021-02-13,2021-02-15 07:19:44,0 days 00:15:34
9,signal lost,2021-02-15 07:19:44,2021-02-15,2021-02-16 09:24:59,0 days 00:50:33
10,signal lost,2021-02-16 09:24:59,2021-02-16,2021-02-18 01:48:55,0 days 00:13:26
11,signal lost,2021-02-18 01:48:55,2021-02-18,2021-02-19 21:36:04,0 days 00:47:35
12,signal lost,2021-02-19 21:36:04,2021-02-19,2021-02-22 09:58:49,0 days 00:12:33
13,signal lost,2021-02-22 09:58:49,2021-02-22,NaT,0 days 00:59:46

In [35]:
signal_monitoring["outage_length"] = signal_monitoring["event_end_date_time"] - signal_monitoring["event_date_time"]
signal_monitoring

,event_type,event_date_time,event_date,event_end_date_time,outage_length
0,signal lost,2021-02-03 00:40:08,2021-02-03,2021-02-03 01:14:11,0 days 00:34:03
1,signal lost,2021-02-05 19:14:19,2021-02-05,2021-02-05 19:46:29,0 days 00:32:10
2,signal lost,2021-02-06 14:31:34,2021-02-06,2021-02-06 14:48:24,0 days 00:16:50
3,signal lost,2021-02-08 04:59:20,2021-02-08,2021-02-08 05:38:29,0 days 00:39:09
4,signal lost,2021-02-09 14:21:25,2021-02-09,2021-02-09 14:42:22,0 days 00:20:57
5,signal lost,2021-02-09 20:07:49,2021-02-09,2021-02-09 20:31:30,0 days 00:23:41
6,signal lost,2021-02-12 03:49:42,2021-02-12,2021-02-12 04:26:48,0 days 00:37:06
7,signal lost,2021-02-12 16:53:17,2021-02-12,2021-02-12 17:18:18,0 days 00:25:01
8,signal lost,2021-02-13 21:15:48,2021-02-13,2021-02-13 21:31:22,0 days 00:15:34
9,signal lost,2021-02-15 07:19:44,2021-02-15,2021-02-15 08:10:17,0 days 00:50:33
10,signal lost,2021-02-16 09:24:59,2021-02-16,2021-02-16 09:38:25,0 days 00:13:26
11,signal lost,2021-02-18 01:48:55,2021-02-18,2021-02-18 02:36:30,0 days 00:47:35
12,signal lost,2021-02-19 21:36:04,2021-02-19,2021-02-19 21:48:37,0 days 00:12:33
13,signal lost,2021-02-22 09:58:49,2021-02-22,2021-02-22 10:58:35,0 days 00:59:46

In [43]:
signal_monitoring["event_date"].value_counts()

event_date
2021-02-12    2
2021-02-09    2
2021-02-03    1
2021-02-05    1
2021-02-08    1
2021-02-06    1
2021-02-13    1
2021-02-15    1
2021-02-16    1
2021-02-18    1
2021-02-19    1
2021-02-22    1
Name: count, dtype: int64

In [44]:
signal_monitoring.groupby("event_date")["outage_length"].sum()

event_date
2021-02-03   0 days 00:34:03
2021-02-05   0 days 00:32:10
2021-02-06   0 days 00:16:50
2021-02-08   0 days 00:39:09
2021-02-09   0 days 00:44:38
2021-02-12   0 days 01:02:07
2021-02-13   0 days 00:15:34
2021-02-15   0 days 00:50:33
2021-02-16   0 days 00:13:26
2021-02-18   0 days 00:47:35
2021-02-19   0 days 00:12:33
2021-02-22   0 days 00:59:46
Name: outage_length, dtype: timedelta64[ns]

## Cvičení

### Půlmaraton

In [62]:
half_maraton = pd.read_csv("half_marathon.csv")
half_maraton.head()

            Jmeno  Rocnik       Cas  Rok zavodu
0  Aster Vladimír    1965  01:53:25        2019
1  Aster Vladimír    1965  02:00:19        2020
2   Asterová Jana    1974  02:16:59        2019
3   Asterová Jana    1974  02:30:01        2020
4   Baborová Anna    1990  01:58:20        2019

In [63]:
half_maraton["Cas"] = pd.to_datetime(half_maraton["Cas"])

C:\Users\Aneta\AppData\Local\Temp\ipykernel_28028\2776535000.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  half_maraton["Cas"] = pd.to_datetime(half_maraton["Cas"])

In [64]:
half_maraton["Cas_2019"] = half_maraton["Cas"].shift(1)

In [66]:
half_maraton = half_maraton[half_maraton["Rok zavodu"] == 2020]

In [67]:
half_maraton["Rozdil_v_case"] = (half_maraton["Cas"] - half_maraton["Cas_2019"]).dt.total_seconds()

C:\Users\Aneta\AppData\Local\Temp\ipykernel_28028\1108411934.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  half_maraton["Rozdil_v_case"] = (half_maraton["Cas"] - half_maraton["Cas_2019"]).dt.total_seconds()

In [68]:
print("Průměrná změna v sekundách: ", half_maraton["Rozdil_v_case"].mean())
print("Průměrná změna v minutách: ", half_maraton["Rozdil_v_case"].mean() /60)
print("Průměrná absolutní změna v minutách: ", half_maraton["Rozdil_v_case"].abs().mean() /60)

Průměrná změna v sekundách:  576.0315789473684
Průměrná změna v minutách:  9.600526315789473
Průměrná absolutní změna v minutách:  10.785438596491227

### Swing states

In [45]:
data = pd.read_csv("election-data.csv")
data = data[data["rank"] == 1]

In [46]:
data_pen = data[data["state"] == "PENNSYLVANIA"]
data_pen["party_simplified_previous_election"] = data_pen["party_simplified"].shift()
data_pen = data_pen.dropna()
data_pen["swing"] = data_pen["party_simplified"] != data_pen["party_simplified_previous_election"]
data_pen[data_pen["swing"] == 1]

C:\Users\Aneta\AppData\Local\Temp\ipykernel_28028\584033968.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_pen["party_simplified_previous_election"] = data_pen["party_simplified"].shift()

,year,state,candidate,party_simplified,candidatevotes,rank,party_simplified_previous_election,swing
3234,1980,PENNSYLVANIA,"REAGAN, RONALD",REPUBLICAN,2261872,1.00,DEMOCRAT,True
3254,1992,PENNSYLVANIA,"CLINTON, BILL",DEMOCRAT,2239164,1.00,REPUBLICAN,True
3288,2016,PENNSYLVANIA,"TRUMP, DONALD J.",REPUBLICAN,2970733,1.00,DEMOCRAT,True
3293,2020,PENNSYLVANIA,"BIDEN, JOSEPH R. JR",DEMOCRAT,3458229,1.00,REPUBLICAN,True

In [47]:
data_pen["swing"].sum()

np.int64(4)

In [48]:
data["party_simplified_previous_election"] = data.groupby("state")["party_simplified"].shift(1)
data = data.dropna()
data["swing"] = data["party_simplified"] != data["party_simplified_previous_election"]
data.groupby("state")["swing"].sum().sort_values(ascending=False)

state
FLORIDA                 5
OHIO                    5
GEORGIA                 4
PENNSYLVANIA            4
WISCONSIN               4
IOWA                    4
KENTUCKY                3
COLORADO                3
LOUISIANA               3
ARIZONA                 3
ARKANSAS                3
NEVADA                  3
NEW HAMPSHIRE           3
MISSOURI                3
NEW MEXICO              3
MICHIGAN                3
WEST VIRGINIA           3
NORTH CAROLINA          3
TENNESSEE               3
DELAWARE                2
INDIANA                 2
HAWAII                  2
RHODE ISLAND            2
NEW YORK                2
MONTANA                 2
MASSACHUSETTS           2
MARYLAND                2
WASHINGTON              1
VIRGINIA                1
TEXAS                   1
NEW JERSEY              1
CONNECTICUT             1
CALIFORNIA              1
ALABAMA                 1
ILLINOIS                1
VERMONT                 1
MAINE                   1
SOUTH CAROLINA          1
OREGON                  1
MISSISSIPPI             1
IDAHO                   0
DISTRICT OF COLUMBIA    0
ALASKA                  0
KANSAS                  0
NORTH DAKOTA            0
MINNESOTA               0
NEBRASKA                0
SOUTH DAKOTA            0
OKLAHOMA                0
UTAH                    0
WYOMING                 0
Name: swing, dtype: int64